name: 'monorepo-publish-action'
description: 'A github action to publish packages in a monorepo.'
author: 'tada5hi'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  token:
    description: 'Token to access registry'
  registry:
    description: 'Registry url'
  cwd:
    description: 'Directory of root package'

runs:
  using: node20
  main: dist/index.js
